- name: Generate SSH key for current user
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
  register: user_info

- debug:
    var: user_info

- name: Add authorized key to remote
  authorized_key:
    user: root
    state: present
    key: "{{ user_info.ssh_public_key }}"
  delegate_to: "{{ item }}"
  become: true
  when: item != inventory_hostname
  with_items: "{{ groups['linux'] }}"
- debug:
    var: inventory_hostname

- debug:
    var: ansible_facts['eth0']['ipv4']['address']

- debug:
    var: ansible_facts['ssh_host_key_rsa_public']

- set_fact:
    host_key_rsa: "{{ inventory_hostname }},{{ ansible_facts['eth0']['ipv4']['address'] }} ssh-rsa {{ ansible_facts['ssh_host_key_rsa_public'] }}"

- debug:
    var: host_key_rsa


- name: tell the host about our servers it might want to ssh to with hostnames
  known_hosts:
    path: /root/.ssh/known_hosts
    name: "{{ inventory_hostname }}"
    key: "{{ host_key_rsa }}"
  delegate_to: "{{ item }}"
  become: true
  when: item != inventory_hostname
  with_items: "{{ groups['linux'] }}"
